### ISSUE TITLE
Add info to the cm attach command

### ISSUE THREAD

**Issue by ipbabble** [stolostron/cm-cli#120]
Currently the `cm attach cluster <cluster-name> --cluster-kubeconfig=<kubecconfig>`  command provides to feedback to the user that the command worked or has been submitted successfully.

1.  Add a short std out message to say that the attach has been dispatched successfully or if the command failed to dispatch to the cluster correctly. Not sure how much the cli knows at this stage that it could report but something is better than nothing. Maybe a message to go check the UI for the klusterlet pod or maybe see the open-cluster-management-agent project. 
2. Add a --wait option that would wait until the command was successful/failed. And provide some output along the way. Suggested output might display that agent functionality and agent add-on functionality has been deployed. What I mean by that is that the user likely doesn't know what agent or agent-add on does. So rather than say the agent has been deployed say what that means from a  status perspective. Similarly with agent-addon. 

So we want some sort of feedback to the user. Something that indicates progress or eventual success/failure. And something in terms of functionality semantics.  (does that make sense?) It might also be useful to have the explicit agent/agent-add failed message embedded in the output for use with debugging/debuggers.

**Comment by itdove** [comment]
Hi @ipbabble 
1. An error is returned if the cm-cli didn't succeed to dispatch the requests to import a cluster as the actual import is done by controllers behind the scene... it is async.
2. Yes we can add a --wait to wait that the managedcluster CR get the correct status "Ready".

**Comment by itdove** [comment]
I hold on the wait-addons as it requires to import all lot of all addons packages and their dependencies in order to check if the all addons are ready.
