### ISSUE TITLE
cm attach should handle kubeconfig blobs

### ISSUE THREAD

**Issue by cdoan1** [stolostron/cm-cli#173]
Hi Team, cm is perfect for automating attach clusters. However, we currently support getting kubeconfig from a file. Would it be possible to accept kubeconfig as a string, and then, also optionally, base64 string to keep these a little more secure? 

```
oc get secret $(oc get hc acmsre-hyper-36 -n clusters --no-headers | awk '{print $3}') -n clusters -ojsonpath='{.data.kubeconfig}' | base64 --decode > kubeconfig.temp

cm attach cluster acmsre-hyper-36 --cluster-kubeconfig=./kubeconfig.temp
```

**Comment by itdove** [comment]
why not create a cmd `cm attach hostedcluster <cluster_name>` ?

**Comment by itdove** [comment]
@cdoan1 Now a parameter --cluster-kubeconfig-content is added to the `cm attach cluster` cmd.
This will be part of the next version but meanwhile you can clone the repo and run `make build` to install the latest `cm`.

I created a new issue for the `cm attach hostedcluster` https://github.com/stolostron/cm-cli/issues/182

**Comment by cdoan1** [comment]
sorry i missed the comment about cm attach hostedcluster <clustername> . That would work too, what ever is easier
